### ISSUE TITLE
Does not support /deep/ in Angular Components

### ISSUE THREAD

**Issue by Ne-Ne** [shinnn/vscode-stylelint#59]
# Issue

When using /deep/ to pierce though into elements without angular bindings this plugin keeps expecting a `}` and a `at-rule or selector expected` notice.

When I run a gulp task these are not present. I believe this to be isolated to an plugin problem.

# Screenshot

![stylelint-deep-issue](https://cloud.githubusercontent.com/assets/2177851/23793771/d43fcc98-0584-11e7-8fb6-fb551f4181a6.png)

# Test Code

```scss
:host{
    /deep/ {
        display: none;
    }
}
```

Regards,

Neil
