### ISSUE TITLE
Style errors not visible in editor

### ISSUE THREAD

**Issue by aesprice** [shinnn/vscode-stylelint#96]
My editor is showing no red highlights for lint errors in my css/scss files (indendation, no-eol-whitespace, etc.). I do, however, see syntax errors, such as:
`margin-bottom:: 10px;`
which has the red underline and reads this when I hover:
`[stylelint] Double Colon (CssSyntaxError)`

The CLI version of stylelint works fine, I see all the errors I expect.

Here's my `.stylelintrc` yml (it's not much):
```
extends: stylelint-config-standard
plugins:
    - stylelint-scss
rules:
    rule-empty-line-before: null
    declaration-empty-line-before: null
    at-rule-no-unknown: null
    scss/at-rule-no-unknown: true
```

About the only other noteworthy thing about my configuration is that it's not in the project's root directory, it's two folders deep. But that doesn't stop the CLI from working from the root, nor does it stop stylelint configuration errors from popping up if my `.stylelintrc` is invalid (for example, if I use `extends: not-a-real-config`). I've been over the documentation and options, and if I'm doing something wrong, I don't know what it is.
